version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"  # Frontend (React)
      - "5000:5000"  # Backend (Express.js)
    env_file:
      - backend/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
